### ISSUE TITLE
[REQUEST]: Implement events, speakers and schedule model for event application

### ISSUE THREAD

**Issue by n1rjal** [GNOME-Nepal/site-server#23]
### Reference Issues

#20 

### Summary

Use this issue to get the event information.

### Basic Example

Use this issue to disccuss about the models of events 

### Drawbacks

Here we will just talk about models of events application

**Comment by Sailesh-Singh** [comment]
PR #31  has been opened to address this issue #23. Please review the changes, and let us know if there are any additional modifications needed. Once merged, this issue should be resolved!
