### ISSUE TITLE
[ISSUES]: Redundant Method Definitions in EventModelAdmin Class

### ISSUE THREAD

**Issue by PublisherName** [GNOME-Nepal/site-server#57]
### Description

In the [admin.py](https://github.com/GNOME-Nepal/site-server/blob/a762b80e2be06eb1d997e1cc9b47d5dc34b61066/event/admin.py) file, the [EventModelAdmin](https://github.com/GNOME-Nepal/site-server/blob/a762b80e2be06eb1d997e1cc9b47d5dc34b61066/event/admin.py#L28) class has multiple redundant definitions of the **get_rsvp_url** method. This redundancy can lead to confusion and potential maintenance issues.

https://github.com/GNOME-Nepal/site-server/blob/a762b80e2be06eb1d997e1cc9b47d5dc34b61066/event/admin.py#L62-L84

# Fixes

Remove the redundant definitions of the [get_rsvp_url](vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) method, keeping only one definition.

**Comment by n1rjal** [comment]
@rex9840 go ahead in with this one as we don't need RSVP URL in list. 
You can see this in single event page.
<img width="799" alt="image" src="https://github.com/user-attachments/assets/20e0d2b0-7763-4769-aebb-10779bde2491">

**Comment by rex9840** [comment]
@n1rjal  will remove from the list display

**Comment by rex9840** [comment]
> undant definitions of the get_rsvp_url method, keeping only one definition.

Seems it was generated form the rebase while resollving some conflict will look into it  asaap

**Comment by rex9840** [comment]
@PublisherName  done with the changes
