### ISSUE TITLE
[ISSUE]: Warnings in GitHub Actions Workflow

### ISSUE THREAD

**Issue by PublisherName** [GNOME-Nepal/site-server#64]
### Description

The GitHub Actions workflow is generating warnings related to Python version and cache paths in Lint workflow. And "deprecated Node.js version" use in CI workflow. 

![Screenshot From 2024-11-10 19-51-10](https://github.com/user-attachments/assets/86b94999-6e65-4123-8b0d-779c4d8036a0)
![Screenshot From 2024-11-10 19-51-27](https://github.com/user-attachments/assets/08ddf2f7-1a7d-4d83-9efb-a8fdaedae5ab)

**Comment by n1rjal** [comment]
As it is just a warning. It's a low priority

**Comment by n1rjal** [comment]
Just saw you have created a PR, thanks.
