### ISSUE TITLE
[BUG]: Date Invisible in Light Mode on Event Calendar

### ISSUE THREAD

**Issue by Sailesh-Singh** [GNOME-Nepal/site-server#70]
### Description

The event calendar on the GNOME Nepal site has a visibility issue where the dates are not visible in light mode but appear correctly in dark mode. This impacts the usability of the calendar, especially for users who prefer light mode.

**Expected Behavior:**
The dates should be visible and legible in both light and dark modes.

**Actual Behavior:**
The dates are invisible in light mode, making it difficult to use the calendar effectively.

**Proposed Solution:**
Update the calendar's CSS to ensure the text color of the dates contrasts sufficiently with the background in both light and dark modes.

### Reproduction URL

https://nepal.gnome.org/#events

### Reproduction steps

```bash
1. Navigate to the GNOME Nepal site and view the event calendar.
2. Switch to light mode.
3. Observe that the dates are not visible.
4. Switch to dark mode.
5. Observe that the dates appear correctly.
```

### Screenshots

```bash
![Invisible in Lightmode](https://github.com/user-attachments/assets/7d82d51b-919a-4b58-9b19-d349d2c091ff)
![Visible in Darkmode](https://github.com/user-attachments/assets/34a41953-58bc-4a06-a536-5fc452c834f9)
```

### OS

Linux

**Comment by n1rjal** [comment]
I believe this is more of a frontend issue. Please raise it in the frontend repository.

**Comment by Sailesh-Singh** [comment]
Yes, I raised this issue there.
